### ISSUE TITLE
Support direct types

### ISSUE THREAD

**Issue by reggi** [okunishinishi/node-argx#1]
@okunishinishi  What are your thoughts on supporting object types directly? Like this:

``` javascript
var CustomError = require(message){
  this.message = message; // String
}

CustomError.prototype = Object.create(Error.prototype);

function(){
  var args = argx(arguments)
  var fn = args.shift(Function)
  var error = args.shift(CustomError)
  var obj = args.shift(Object)
}
```

**Comment by okunishinishi** [comment]
@reggi 
Thanks, direct types are now supported in [version 1.1.0](https://github.com/okunishinishi/node-argx/commit/fed170bb22dfe77ab5e34d14e9a1da1643a06d72)
