### ISSUE TITLE
Support type "or"

### ISSUE THREAD

**Issue by reggi** [okunishinishi/node-argx#2]
@okunishinishi  What are your thoughts on supporting multiple options for an argument? Like this:

``` javascript
function(){
  var args = argx(arguments)
  var value = args.shift(["string", "boolean"]) // shifts the first string or boolean
}
```

**Comment by okunishinishi** [comment]
@reggi 

Thanks, now supported in [v1.1.1](https://github.com/okunishinishi/node-argx/commit/8f4d38693ea1deb1fdd28114a9861025834c22f5)

There are two ways to specify **_'or'**_ condition for types.
1. Passing string joined by `"|"` 
2. Passing array

``` javascript
var args = argx(arguments)
value = args.shift("string|boolean");
value = args.shift(["string", MyCustomObj]);
```

**Comment by reggi** [comment]
Words cannot express how grateful I am, thank you so much!
